[package]
name = "projects_backend_database"
version = "0.5.0"
edition = "2024"

[features]
default = []
frontend_resume_editor_svelte = ["api/frontend_resume_editor_svelte"]

[dependencies]
api = { path = "./api" }
infrastructure = { path = "./infrastructure" }
shared = { path = "./shared" }
clap = { version = "4.5.23", features = ["derive", "cargo"] }
rand = "0.10.0"
rocket = { version = "0.5.1" }
log = "0.4.28"

[workspace]
members = ["api", "domain", "infrastructure", "application", "shared", "api_playground"]
